name: Bilibili Dynamic Check

on:
  schedule:
    - cron: "0 * * * *"  # 每小时运行一次
  workflow_dispatch:     # 允许手动触发

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install requests

    - name: Run checker
      run: python check_dynamic.py

    - name: Deploy to GitHub Pages
      run: |
        cp bilibili_dynamic.rss ./docs/
        git add ./docs/bilibili_dynamic.rss
        git commit -m "Update RSS feed"
        git push
