name: Bilibili Dynamic Check

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:  # 新增权限配置
  actions: write
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install requests

    - name: Generate RSS
      run: |
        python check_dynamic.py
        ls -la  # 验证文件生成

    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # 升级到v4版本
      with:
        name: bilibili-rss
        path: |
          bilibili_dynamic.rss
          last_dynamic_id.txt
        retention-days: 7

    - name: Clean history artifacts
      uses: c-hive/gha-remove-artifacts@v1  # 更换更可靠的清理Action
      with:
        pattern: 'bilibili-rss'
        keep-latest: 5
