name: Bilibili Dynamic Check

on:
  schedule:
    - cron: "2 4 * * *"
  workflow_dispatch:

permissions:  # 新增权限配置
  actions: write
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install requests,feedgen

    - name: Generate RSS
      run: |
        python check_dynamic.py
        ls -la  # 验证文件生成

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.email "kfalskdf@4171614.xyz"
        git config --global user.name "kfalskdf"
        mkdir -p ./docs  # 创建 Pages 专用目录
        cp bilibili_dynamic.rss ./docs/
        git add ./docs/bilibili_dynamic.rss
        git commit -m "Update RSS feed"
        git push

    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # 升级到v4版本
      with:
        name: bilibili-rss
        path: |
          bilibili_dynamic.rss
          last_dynamic_id.txt
        retention-days: 7

