name: Bilibili Dynamic Check

on:
  schedule:
    - cron: "0 * * * *"  # 每小时运行一次
  workflow_dispatch:     # 允许手动触发

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install requests

    - name: Generate RSS
      run: python check_dynamic.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: bilibili-rss
        path: |
          bilibili_dynamic.rss
          last_dynamic_id.txt
        retention-days: 7  # 自定义保留天数（默认90天）

    - name: Clean history artifacts
      if: always()
      uses: geekyeggo/delete-artifact@v1
      with:
        name: bilibili-rss
        keep-latest: 5  # 仅保留最新5个记录
